config/routes.rb
Layolette::Application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", confirmations: "users/confirmations" }
  devise_scope :user do
    put "/confirm" => "users/confirmations#confirm"
  end

  get "home/index"

  resources :users do
    resources :reservations, only: [:index]
  end
  resources :reservations, only: [:index, :show, :new, :create, :update, :destroy]

  root to: 'home#index'

  get '/help'      => 'home#help'

  match '/contact' => 'contact#new',    :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post
  match '/contact' => 'contact#update', :as => 'contact', :via => :put

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :jour, :creneau_id, :aviron_id, :confirmation, :responsable_id

  belongs_to :creneau
  belongs_to :aviron
  belongs_to :user, class_name: "User", foreign_key: "responsable_id"
  has_many :registres, dependent: :destroy
  has_many :users, through: :registres

  validates :jour, presence: true
  validates :creneau_id, presence: true
  validates :aviron_id, presence: true
  validate :empty_place, :jour_cannot_be_after_3months

  scope :recent, -> { where("reservations.jour >= ?", Date.today) }
  scope :asc,    -> attr { order("reservations.#{attr} ASC") }

  private
    def empty_place
      errors.add(:aviron, "#{aviron.id} est rempli") if self.users.size > self.aviron.nbplaces
    end

    def jour_cannot_be_after_3months
      errors.add(:jour, "ne peut pas être au delà de 3 mois") if self.jour > (Date.today+3.months)
    end
end

app/controllers/reservations_controller.rb
include ReservationsHelper

class ReservationsController < ApplicationController
  before_action :set_reservation,           only: [:show, :update, :destroy]
  
  before_filter :authenticate_user!
  before_filter :check_params,              only: :create
  before_filter :subscribed_to_reservation, only: [:show, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.recent.asc("jour").paginate(page: params[:page], per_page: 30)
    @user = User.find(params[:user_id]) if params[:user_id].present?

    respond_to do |format|
      format.html { @reservations }
      format.json {
        render json: {
          current_page:  @reservations.current_page,
          per_page:      @reservations.per_page,
          total_entries: @reservations.total_entries,
          entries:       @reservations
        }
      }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        @reservation.users << current_user
        flash[:changed_reservation] = @reservation.id

        format.html { redirect_to reservations_url, notice: "Réservation enregistrée" }
        format.json { render action: 'index', status: :created, location: reservations_url }
      else
        format.html { render action: 'new' }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    if params[:from_page] == "index"
      flash[:changed_reservation] = @reservation.id
      if params[:participate] == "yes"
        @reservation.users << current_user
        message = "Félicitations, vous faites partie de l'équipage"
      else
        @reservation.users.delete(current_user)
        message = "Vous avez quitté l'équipage"
      end
      respond_to do |format|
        format.html { redirect_to reservations_url, notice: message }
        format.json { render action: 'index', status: :updated, location: reservations_url }
      end

    elsif params[:reservation][:from_page] == "show"
      if @reservation.confirmation
        message = "Réservation déjà confirmée"
        respond_to do |format|
          format.html { redirect_to reservation_url(@reservation), alert: message }
          format.json { render action: 'show', alert: message, location: reservation_url(@reservation) }
        end
      else
        @reservation.confirmation = true
        @reservation.responsable_id = current_user.id
        respond_to do |format|
          if @reservation.save
            nb_users = @reservation.users.size
            if nb_users > 1
              # Notify the users
              contact = Contact.new
              contact.build(current_user, "")
              @reservation.users.each do |user|
                UserMailer.notify_reservation_email(contact, user, @reservation).deliver if user.id!=current_user.id
              end
            end

            message = "Réservation confirmée"
            if nb_users > 1
              message += ", tous les users ont été notifiés par mail"
            end
            format.html { redirect_to reservation_url(@reservation), notice: message }
            format.json { render action: 'show', status: :updated, location: reservation_url(@reservation) }
          else
            format.html { render action: 'show' }
            format.json { render json: @reservation.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Réservation annulée" }
      format.json { head :no_content, status: :success }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:jour, :creneau_id, :aviron_id)
    end

    # Check the conformity of the crenau with the aviron type
    def check_params
      jour = reservation_params[:jour]
      creneau_id = reservation_params[:creneau_id]

      flash[:jour] = jour
      flash[:creneau_id] = creneau_id
      flash[:aviron_id] = reservation_params[:aviron_id]

      jour_date = Date.parse(jour) rescue nil

      if jour_date.nil?
        flash[:jour] = Date.today.strftime('%d-%m-%Y')
        is_valid = false
        message = "Le jour de réservation n'est pas valide"
      elsif jour.to_date < Date.today
        is_valid = false
        message = "Le jour de réservation doit être postérieur à aujourd'hui"
      elsif creneau_id.include?("---") || creneau_id==""
        is_valid = false
        message = "Le créneau horaire que vous avez choisi est incorrect"
      else
        creneau = Creneau.find(creneau_id)
        aviron = Aviron.find(reservation_params[:aviron_id])

        delta = creneau.fin - creneau.debut
        is_valid = delta==45.minutes && (aviron.description=="simple" || aviron.description=="double")
        is_valid ||= delta==1.hour && aviron.description=="yolette"

        message = "Le créneau horaire que vous avez choisi ne correspond pas au type d'aviron"
      end

      unless is_valid
        respond_to do |format|
          format.html { redirect_to new_reservation_path, alert: message }
          format.json { render 'new', status: :unauthorized, alert: message }
        end
      end
    end

    # Verify that the current user is subscribed to the reservation he tries to show
    def subscribed_to_reservation
      unless subscribed?(@reservation)
        message = "Vous n'êtes pas inscrit(e) à cette réservation"
        respond_to do |format|
          format.html { redirect_to reservations_url, alert: message }
          format.json { render 'show', status: :unauthorized, alert: message }
        end
      end
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
	
	def aviron_types
		Aviron.uniq(:nbplaces).asc("nbplaces").map do |aviron|
			[aviron.description, aviron.id]
		end
	end

	def creneau_times
		creneaux = Creneau.asc("debut")
		simple_double = creneaux.map do |creneau|
			["#{creneau.debut.strftime('%H:%M')}-#{creneau.fin.strftime('%H:%M')}",
			creneau.id] if creneau.fin-creneau.debut == 45.minutes
		end.select { |c| c }
		yolette = creneaux.map do |creneau|
			["#{creneau.debut.strftime('%H:%M')}-#{creneau.fin.strftime('%H:%M')}",
			creneau.id] if creneau.fin-creneau.debut == 1.hour
		end.select { |c| c }

		[["--- horaires simple et double ---", nil]] + simple_double + [["--- horaires yolette ---", nil]] + yolette
	end

	def display_creneau(creneau)
		"#{creneau.debut.strftime('%H:%M')}-#{creneau.fin.strftime('%H:%M')}"
	end

	def changed_reservation?(reservation)
		reservation.id == flash[:changed_reservation]
	end

	def equipage(reservation)
		reservation.users.map do |user|
      user.prenom
    end.join(", ")
	end

	def empty_place?(reservation)
		reservation.aviron.nbplaces > reservation.users.size
	end

	def subscribed?(reservation)
		reservation.users.each do |r|
			return true if r.id == current_user.id
		end
		false
	end

	def resa_class(reservation)
		is_empty_place = empty_place?(reservation)
		days_left = (reservation.jour - Date.today).days

		resa_class = []
		resa_class << "new_resa" if changed_reservation?(reservation)
		if is_empty_place && days_left<=1.day
			resa_class << "error"
		elsif is_empty_place && days_left<=1.week
			resa_class << "warning"
		elsif !is_empty_place
			resa_class << "success"
		end

		resa_class * " "
	end

	def build_button(reservation)
		button_params = {}
		button_params[:participate] = "yes"
		button_params[:action]      = :put
		button_params[:text]        = "Participer"
		button_params[:disabled]    = false

		if subscribed?(reservation)
			button_params[:participate] = "no"
			button_params[:action]      = :delete if reservation.users.size == 1
			button_params[:text]        = "Désister  "
		elsif !empty_place?(reservation)
			button_params[:participate] = "no"
			button_params[:disabled]    = true
		end

		return button_params
	end

	def responsable_confirmation(reservation)
		message = "Confirmée au téléphone"
		responsable = User.find_by_id(reservation.responsable_id)
		if responsable && reservation.users.size > 1
			message += " par"
			if responsable == current_user
				message += " moi"
			else
				message += " #{responsable.nom} #{responsable.prenom}"
			end
		end
		message
	end

	def confirmation_message_group(reservation)
		message = "Cette action est irreversible."
		if reservation.users.size > 1
			message += " Si vous la validez, les users inscrits seront notifiés par mail."
		end
		message += " Etes-vous sûrs de vouloir continuer ?"
	end
end

app/views/reservations/_form.html.erb
<div class="row">
  <div class="span9 offset2">
    <%= form_for(@reservation) do |f| %>
      <% if @reservation.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-error">
            <strong><%= pluralize(@reservation.errors.count, "erreur") %> :</strong>
            <ul>
              <% @reservation.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="row reservations">
        <div class="span2 field">
          <%= f.label :jour %><br />
          <%= f.text_field :jour, class: "input-append date datepicker", value: flash[:jour].present? && flash[:jour].to_date>Date.today ? flash[:jour] : Date.today.strftime('%d-%m-%Y') %>
          <!-- div class="input-append date datepicker">
            <input size="16" type="text" value= <%= "06-05-2013" %> >
            <span class="add-on"><i class="icon-th"></i></span>
          </div -->
        </div>
        <div class="span4 field">
          <%= f.label :creneau_id %><br />
          <%= f.select :creneau_id, creneau_times, selected: flash[:creneau_id] %>
        </div>
        <div class="span2 field">
          <%= f.label :aviron_id %><br />
          <%= f.select :aviron_id, aviron_types, selected: flash[:aviron_id] %>
        </div>
        <!-- <div class="field">
          <%= f.label :confirmation %><br />
          <%= f.check_box :confirmation %>
        </div> -->
      </div>
      <div class="row">
        <div class="span2 offset3 actions">
          <br />
          <%= f.submit "Réserver", class: "btn btn-large btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>N°</th>
      <th></th>
      <th>Jour</th>
      <th>Créneau</th>
      <th>Aviron</th>
      <th>Users</th>
      <th></th>
    </tr>
  </thead>
  <tbody class="reservation"><p>
    <% @reservations.each do |reservation| %>
      <% subscribed = subscribed?(reservation) %>
      <% if @user && subscribed || !@user %>
        <tr class="<%= resa_class(reservation) %>" >
          <td><%= reservation.id %></td>
          <td>
            <% if subscribed %>
              <a href=<%= reservation_path(reservation) %> >
                <%= image_tag "glyphicons_003_user.png", alt: "user" %>
              </a>
            <% end %>
            <% if reservation.confirmation %>
              <%= image_tag "glyphicons_163_iphone.png", alt: "phone" %>
            <% end %>
          </td>
          <td><%= reservation.jour.strftime("%d/%m/%y") %></td>
          <td><%= display_creneau(reservation.creneau) %></td>
          <td><%= reservation.aviron.description %></td>
          <td><%= equipage(reservation) %></td>

          <% button_params = build_button(reservation) %>
          <%= form_tag reservation_path(reservation), method: button_params[:action] do %>
            <%= hidden_field_tag :from_page, "index" %>
            <%= hidden_field_tag :participate, button_params[:participate] %>
            <td>
              <%= submit_tag button_params[:text], disabled: button_params[:disabled], class: "btn btn-small" %>
            </td>
          <% end %>

        </tr>
      <% end %>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= link_to "Proposer", new_reservation_path, class: "btn btn-small" %></td>
    </tr>
  </tbody>
</table>

app/views/reservations/edit.html.erb
<% provide(:title, "Réservation") %>

<div class="row">
	<div class="span5">
		<h1>Réservation <%= @reservation.id %></h1>
	</div>
</div>

<div class="row">
	<div class="span11">

		<div class="span5">

			<div class="row">
				<div class="span2">
				  <strong>Jour:</strong>
				</div>
				<div class="span2">
				  <%= @reservation.jour.strftime("%d/%m/%Y") %>
				</div>
				<div class="span2">
				  <strong>Créneau:</strong>
				</div>
				<div class="span2">
				  De
				  <%= @reservation.creneau.debut.strftime("%H:%M") %>
				  à
				  <%= @reservation.creneau.fin.strftime("%H:%M") %>
				</div>
				<div class="span2">
				  <strong>Aviron:</strong>
				</div>
				<div class="span2">
				  <%= pluralize(@reservation.aviron.nbplaces, "place") %>
				</div>
				<div class="span2">
				  <strong>Confirmation:</strong>
				</div>
				<div class="span2">
				  <%= @reservation.confirmation ? "Oui" : "Non" %>
				</div>
			</div>
			<br /><br />

			<div class="row">
				<div class="span1 center">
					<%= image_tag "glyphicons_163_iphone.png", alt: "phone" %>
				</div>
				<div class="span4">
					<% if @reservation.confirmation %>
						<p><%= responsable_confirmation(@reservation) %></p>
					<% else %>
						<%= form_for(@reservation) do |f| %>
	            <%= f.hidden_field :from_page, value: "edit" %>
							<%= f.submit "J'ai réservé par téléphone", class: "btn btn-small btn-info", data: { confirm: confirmation_message_group(@reservation) } %>
						<% end %>
					<% end %>
				</div>
			</div>
			<br/>

			<% if @reservation.users.size > 1 %>
				<div class="row">
					<div class="span1 center">
						<%= image_tag "glyphicons_043_group.png", alt: "groupe" %>
					</div>
					<div class="span3">
	          <%= form_tag contact_path, method: :put do %>
	            <%= hidden_field_tag :reservation_id, @reservation.id %>
	            <%= hidden_field_tag :destination, "group" %>
	            <%= text_area_tag :content %>
	            <%= submit_tag "Je contacte le groupe", class: "btn btn-small btn-info" %>
	          <% end %>
					</div>
				</div>
				<br/>
			<% end %>

			<% if @reservation.aviron.nbplaces > 1 %>
				<div class="row">
					<div class="span1 center">
						<%= image_tag "glyphicons_135_inbox_out.png", alt: "mail users" %>
					</div>
					<div class="span3">
	          <%= form_tag contact_path, method: :put do %>
	            <%= hidden_field_tag :reservation_id, @reservation.id %>
	            <%= hidden_field_tag :destination, "all" %>
	            <%= text_area_tag :content %>
	            <%= submit_tag "Je cherche un user", class: "btn btn-small btn-info", data: { confirm: "Cette action est irreversible. Si vous la validez, tous les users du site seront notifiés par mail. Etes-vous sûrs de vouloir continuer ?" } %>
	          <% end %>
					</div>
				</div>
			<% end %>

		</div>

		<div class="span3">
		  <% @reservation.users.each do |user| %>
				<div class="row">
			  	<%= gravatar_for user %>
				  <br><%= link_to "#{user.nom} #{user.prenom}", user_path(user) %>
				</div>
				<br />
		  <% end %>
		</div>
	</div>

</div>

app/views/reservations/index.html.erb
<% provide(:title, 'Réservations') %>

<% if @user %>
	<h1>Mes réservations</h1>
<% else %>
	<h1>Liste des réservations</h1>
<% end %>

<%= will_paginate_fr @reservations %>

<div class="center hero-unit">
  <%= render 'table' %>
</div>

<br />

<%= will_paginate_fr @reservations %>

app/views/reservations/new.html.erb
<% provide(:title, "Réservervation") %>

<h1>Réserver</h1>

<%= render 'form' %>

app/views/reservations/show.html.erb
<% provide(:title, "Réservation") %>

<div class="row">
	<div class="span5">
		<h1>Réservation <%= @reservation.id %></h1>
	</div>
</div>

<div class="row">
	<div class="span11">

		<div class="span5">

			<div class="row">
				<div class="span2">
				  <strong>Jour:</strong>
				</div>
				<div class="span2">
				  <%= @reservation.jour.strftime("%d/%m/%Y") %>
				</div>
				<div class="span2">
				  <strong>Créneau:</strong>
				</div>
				<div class="span2">
				  De
				  <%= @reservation.creneau.debut.strftime("%H:%M") %>
				  à
				  <%= @reservation.creneau.fin.strftime("%H:%M") %>
				</div>
				<div class="span2">
				  <strong>Aviron:</strong>
				</div>
				<div class="span2">
				  <%= pluralize(@reservation.aviron.nbplaces, "place") %>
				</div>
				<div class="span2">
				  <strong>Confirmation:</strong>
				</div>
				<div class="span2">
				  <%= @reservation.confirmation ? "Oui" : "Non" %>
				</div>
			</div>
			<br /><br />

			<div class="row">
				<div class="span1 center">
					<%= image_tag "glyphicons_163_iphone.png", alt: "phone" %>
				</div>
				<div class="span4">
					<% if @reservation.confirmation %>
						<p><%= responsable_confirmation(@reservation) %></p>
					<% else %>
						<%= form_for(@reservation) do |f| %>
	            <%= f.hidden_field :from_page, value: "show" %>
							<%= f.submit "J'ai réservé par téléphone", class: "btn btn-small btn-info", data: { confirm: confirmation_message_group(@reservation) } %>
						<% end %>
					<% end %>
				</div>
			</div>
			<br/>

			<% if @reservation.users.size > 1 %>
				<div class="row">
					<div class="span1 center">
						<%= image_tag "glyphicons_043_group.png", alt: "groupe" %>
					</div>
					<div class="span3">
	          <%= form_tag contact_path, method: :put do %>
	            <%= hidden_field_tag :reservation_id, @reservation.id %>
	            <%= hidden_field_tag :destination, "group" %>
	            <%= text_area_tag :content %>
	            <%= submit_tag "Je contacte le groupe", class: "btn btn-small btn-info" %>
	          <% end %>
					</div>
				</div>
				<br/>
			<% end %>

			<% if @reservation.aviron.nbplaces > 1 %>
				<div class="row">
					<div class="span1 center">
						<%= image_tag "glyphicons_135_inbox_out.png", alt: "mail users" %>
					</div>
					<div class="span3">
	          <%= form_tag contact_path, method: :put do %>
	            <%= hidden_field_tag :reservation_id, @reservation.id %>
	            <%= hidden_field_tag :destination, "all" %>
	            <%= text_area_tag :content %>
	            <%= submit_tag "Je cherche un user", class: "btn btn-small btn-info", data: { confirm: "Cette action est irreversible. Si vous la validez, tous les users du site seront notifiés par mail. Etes-vous sûrs de vouloir continuer ?" } %>
	          <% end %>
					</div>
				</div>
			<% end %>

		</div>

		<div class="span3">
		  <% @reservation.users.each do |user| %>
				<div class="row">
			  	<%= gravatar_for user %>
				  <br><%= link_to "#{user.nom} #{user.prenom}", user_path(user) %>
				</div>
				<br />
		  <% end %>
		</div>
	</div>

</div>