config/routes.rb
Layolette::Application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", confirmations: "users/confirmations" }
  devise_scope :user do
    put "/confirm" => "users/confirmations#confirm"
  end

  get "home/index"

  resources :users do
    resources :reservations, only: [:index]
  end
  resources :reservations, only: [:index, :show, :new, :create, :update, :destroy]

  root to: 'home#index'

  get '/help'      => 'home#help'

  match '/contact' => 'contact#new',    :as => 'contact', :via => :get
  match '/contact' => 'contact#create', :as => 'contact', :via => :post
  match '/contact' => 'contact#update', :as => 'contact', :via => :put

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Powered by MG
  </small>
  <nav>
    <ul>
      <li><%= link_to "Aide",    help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Sport Event", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li><%= link_to "Membres",     users_path %></li>
            <li><%= link_to "Résevations", reservations_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Mon compte <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profil",           current_user %></li>
                <li><%= link_to "Paramètres",       edit_user_registration_path %></li>
                <li><%= link_to "Mes réservations", user_reservations_path(current_user) %></li>
                <li class="diviser"></li>
                <li><%= link_to "Déconnexion",      destroy_user_session_path, method: "delete" %></li>
              </ul>
          <% else %>
            <li><%= link_to "S'identifier", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

	<%= render 'layouts/header' %>
  <div class="container">

    <% if notice %>
      <div class="row">
        <div class="span8">
          <div id="notice">
            <p class="alert alert-success"><%= notice %></p>
          </div>
        </div>
      </div>
    <% end %>

    <% if alert %>
      <div class="row">
        <div class="span8">
          <div id="notice">
            <p class="alert alert-block"><%= alert %></p>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>